index:
    path:       /
    defaults:   { _controller: BookBundle:Index:index }

user:
    path:       /user
    defaults:   { _controller: BookBundle:Index:user }

admin:
    path:       /admin
    defaults:   { _controller: BookBundle:Index:admin }
