index:
    path:       /
    defaults:   { _controller: BookBundle:Index:index }

user:
    path:       /user
    defaults:   { _controller: BookBundle:Index:user }

admin:
    path:       /admin
    defaults:   { _controller: BookBundle:Index:admin }

register:
    path:       /register
    defaults:   { _controller: BookBundle:Security:register }

create:
    path:       /register/create
    defaults:   { _controller: BookBundle:Security:create }

login:
    path:       /login
    defaults:   { _controller: BookBundle:Security:login }

login_check:
    path:       /login/check
    defaults:   { _controller: BookBundle:Security:loginCheck }
