security:
    encoders:
        BookBundle\Entity\User:   bcrypt

    role_hierarchy:
        ROLE_USER:    ROLE_USER
        ROLE_ADMIN:   [ROLE_USER, ROLE_ADMIN]

    providers:
#        in_memory:
#            memory: ~
        my_db_provider:
            entity:
                class:      BookBundle:User
                property:   username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        default:
            pattern:    ^/
            http_basic: ~
            anonymous:  ~
            provider:   my_db_provider
            form_login:
                login_path:   /login
                check_path:   /login_check

    access_control:
            - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: /index, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/user/, role: ROLE_USER }
            - { path: ^/admin/, role: ROLE_ADMIN }
